# Generated by Django 5.1.3 on 2024-12-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_plataforma_producto_plataformas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('codigoBarra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField(max_length=300)),
                ('foto', models.FileField(upload_to='tarjetas')),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
    ]
